### ISSUE TITLE
Hive metastore Schema initialization FAILED!

### ISSUE THREAD

**Issue by ctyjrsy** [thiagodiogo/presto-on-kubernetes#1]
@thiagodiogo did you do any configuration change anywhere for the K8S deployment to work? I am getting the below error when deploying hive.

Starting metastore schema initialization to 2.1.0
Initialization script hive-schema-2.1.0.postgres.sql
Error: ERROR: relation "BUCKETING_COLS" already exists (state=42P07,code=0)
org.apache.hadoop.hive.metastore.HiveMetaException: Schema initialization FAILED! Metastore state would be inconsistent !!
Underlying cause: java.io.IOException : Schema script failed, errorcode 2
Use --verbose for detailed stacktrace.
*** schemaTool failed ***
Starting Hive Metastore Server
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hive-dist/apache-hive-2.1.0-bin/lib/log4j-slf4j-impl-2.4.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/hadoop-2.7.2/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
java.lang.IllegalArgumentException: java.net.UnknownHostException: hdfs-namenode.presto
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:377)

**Comment by thiagodiogo** [comment]
Hello @ctyjrsy, is your hive PG DB empty?

It looks like your model it's not empty:
> Error: ERROR: relation "BUCKETING_COLS" already exists (state=42P07,code=0)

**Comment by ctyjrsy** [comment]
So when the metastore.yaml creates the PG DB, does it expect any schema or data model to be inserted? I would assume Hive to do the same. I am following the instructions that you provided.

**Comment by thiagodiogo** [comment]
Sorry, just added a DB setup step [here](https://github.com/thiagodiogo/presto-on-kubernetes/commit/129dd161fc49af821026e166d6d161fbfb3cf2c3)

Take a look at the new [README](https://github.com/thiagodiogo/presto-on-kubernetes/blob/master/README.md), item 4.1.

Hope this helps

**Comment by thiagodiogo** [comment]
Closing this for now.
